// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

// `import 'dotenv/config'` loads only `<cwd>/.env`. Load repo-root `.env` relative to this file (cwd-independent).
// `override: false` keeps vars already set in the shell / CI from being replaced by the file.
function loadLedgerEnv(): void {
  // Prisma’s loader executes this file as ESM; NodeNext still typechecks it as CJS-only.
  // @ts-expect-error TS1470 — import.meta is valid at runtime here
  const configDir = dirname(fileURLToPath(import.meta.url));
  const rootEnv = join(configDir, '../.env');
  const localEnv = join(configDir, '.env');
  for (const path of [rootEnv, localEnv]) {
    if (existsSync(path)) {
      config({ path, override: false });
      return;
    }
  }
}
loadLedgerEnv();

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
